export const fakePatients = [
  {
    id: "1",
    sex: "man",
    lastName: "Dupont",
    firstName: "Alain",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "adupont@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal au genou",
    history: "chute à vélo et AVC",
    goals: "retrouver de la mobilité",
    height: 180,
    weight: 65,
    tests: [],
  },
  {
    id: "2",
    sex: "woman",
    lastName: "Doe",
    firstName: "Marie",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "mdoe@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal au coude",
    history: "Arret cardiaque",
    goals: "retrouver de la motivation",
    height: 170,
    weight: 55,
    tests: [],
  },
  {
    id: "3",
    sex: "woman",
    lastName: "Ranik",
    firstName: "Rosalie",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "rranik@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à l'orteil",
    history: "Saut du télésiège",
    goals: "reconquérir son ex",
    height: 150,
    weight: 85,
    tests: [],
  },
  {
    id: "4",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
  {
    id: "5",
    sex: "woman",
    lastName: "Ranik",
    firstName: "Rosalie",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "rranik@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à l'orteil",
    history: "Saut du télésiège",
    goals: "reconquérir son ex",
    height: 150,
    weight: 85,
    tests: [],
  },
  {
    id: "6",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
  {
    id: "7",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
  {
    id: "8",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
  {
    id: "9",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
  {
    id: "10",
    sex: "man",
    lastName: "Pita",
    firstName: "John",
    adress: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "jpita@gmail.com",
    phone: "0123456789",
    birth: "1999-01-01",
    problems: "mal à la narine du milieu",
    history: "Attaque de requin",
    goals: "marquer plus de but au foot",
    height: 174,
    weight: 100,
    tests: [],
  },
]
