export const fakePatients = [
  {
    id: "1",
    sex: "man",
    lastName: "Dupont",
    firstName: "Alain",
    address: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "adupont@gmail.com",
    phone: "0612345678",
    birth: "1965-03-14",
    problems: "Douleurs chroniques au genou droit",
    history: "Chute à vélo en 2018, opération du ménisque en 2019",
    goals: "Retrouver de la mobilité pour reprendre la randonnée",
    height: 180,
    weight: 82,
    bilans: [
      {
        id: "5025152a-3a7f-4f57-a721-0ab67c362786",
        type: "initial",
        date: "2026-02-21",
        tests: [
          {
            name: "Assis-debout",
            remarques: "6czcz8",
            results: [
              {
                field: "Répétitions",
                value: "5",
              },
              {
                field: "FC initiale",
                value: "4",
              },
              {
                field: "FC finale",
                value: "8",
              },
              {
                field: "FC après délai",
                value: "8",
              },
              {
                field: "Sat initiale",
                value: "6",
              },
              {
                field: "Sat finale",
                value: "4",
              },
              {
                field: "Sat après délai",
                value: "5",
              },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "fke",
            results: [
              {
                field: "Durée gauche",
                value: "8",
              },
              {
                field: "Durée droite",
                value: "9",
              },
              {
                field: "FC initiale",
                value: "5",
              },
              {
                field: "FC finale",
                value: "2",
              },
              {
                field: "FC après délai",
                value: "5",
              },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
  {
    id: "2",
    sex: "woman",
    lastName: "Marchand",
    firstName: "Sophie",
    address: {
      cp: "75011",
      city: "Paris",
      street: "14 rue de la Roquette",
    },
    mail: "sophie.marchand@gmail.com",
    phone: "0698765432",
    birth: "1982-07-22",
    problems: "Douleurs à l'épaule gauche post-opératoire",
    history: "Rupture de la coiffe des rotateurs, opérée en janvier 2025",
    goals: "Reprendre le tennis en compétition",
    height: 168,
    weight: 62,
    bilans: [],
    logbook: [],
  },
  {
    id: "3",
    sex: "man",
    lastName: "Bernard",
    firstName: "Luc",
    address: {
      cp: "69003",
      city: "Lyon",
      street: "8 avenue Félix Faure",
    },
    mail: "luc.bernard@hotmail.fr",
    phone: "0645231789",
    birth: "1955-11-30",
    problems: "BPCO stade 2, fatigabilité à l'effort",
    history:
      "Fumeur pendant 30 ans, arrêt en 2010. Hospitalisation pour pneumonie en 2022",
    goals: "Améliorer l'endurance pour les activités quotidiennes",
    height: 172,
    weight: 78,
    bilans: [],
    logbook: [],
  },
  {
    id: "4",
    sex: "woman",
    lastName: "Petit",
    firstName: "Camille",
    address: {
      cp: "33000",
      city: "Bordeaux",
      street: "3 rue des Chartrons",
    },
    mail: "camille.petit@gmail.com",
    phone: "0556123456",
    birth: "1998-04-05",
    problems: "Entorse de cheville récidivante côté gauche",
    history: "3 entorses en 2 ans, kinésithérapie classique insuffisante",
    goals: "Stabiliser la cheville pour reprendre le basket",
    height: 165,
    weight: 58,
    bilans: [],
    logbook: [],
  },
  {
    id: "5",
    sex: "man",
    lastName: "Nguyen",
    firstName: "Thomas",
    address: {
      cp: "31000",
      city: "Toulouse",
      street: "22 rue du Taur",
    },
    mail: "thomas.nguyen@gmail.com",
    phone: "0561987654",
    birth: "1975-09-18",
    problems: "Lombalgies chroniques, hernie discale L4-L5",
    history: "Sédentarité prolongée, travail de bureau. IRM en 2023",
    goals: "Réduire les douleurs et reprendre le vélo",
    height: 176,
    weight: 88,
    bilans: [],
    logbook: [],
  },
]
