export const fakePatients = [
  {
    id: "1",
    sex: "man",
    lastName: "Dupont",
    firstName: "Alain",
    address: {
      cp: "67960",
      city: "Entzheim",
      street: "52B route de Strasbourg",
    },
    mail: "adupont@gmail.com",
    phone: "0612345678",
    birth: "1965-03-14",
    height: 180,
    weight: 82,
    problems: "Douleurs chroniques au genou droit",
    history: "Chute à vélo en 2018, opération du ménisque en 2019",
    goals: "Retrouver de la mobilité pour reprendre la randonnée",
    archived: false,
    bilans: [
      {
        id: "5025152a-3a7f-4f57-a721-0ab67c362786",
        type: "initial",
        height: 180,
        weight: 82,
        imc: 25.3,
        date: "2026-02-21",
        tests: [
          {
            name: "Assis-debout",
            remarques: "6czcz8",
            results: [
              { field: "Répétitions", chart: true, value: "5" },
              { field: "FC initiale", value: "4" },
              { field: "FC finale", value: "8" },
              { field: "FC après délai", value: "8" },
              { field: "Sat initiale", value: "6" },
              { field: "Sat finale", value: "4" },
              { field: "Sat après délai", value: "5" },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "fke",
            results: [
              { field: "Durée gauche", chart: true, value: "8" },
              { field: "Durée droite", chart: true, value: "9" },
              { field: "FC initiale", value: "5" },
              { field: "FC finale", value: "2" },
              { field: "FC après délai", value: "5" },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
  {
    id: "2",
    sex: "woman",
    lastName: "Martin",
    firstName: "Sophie",
    address: {
      cp: "67000",
      city: "Strasbourg",
      street: "14 rue des Roses",
    },
    mail: "sophie.martin@outlook.fr",
    phone: "0698765432",
    birth: "1978-07-22",
    height: 165,
    weight: 62,
    problems: "Lombalgie chronique, fatigue persistante",
    history:
      "Hernie discale L4-L5 diagnostiquée en 2021, kinésithérapie suivie pendant 6 mois",
    goals:
      "Diminuer les douleurs au quotidien et reprendre le travail à plein temps",
    archived: false,
    bilans: [
      {
        id: "b2c3d4e5-f6a7-8901-bcde-f12345678901",
        type: "intermediaire",
        height: 165,
        weight: 62,
        imc: 22.77,
        date: "2026-02-15",
        tests: [
          {
            name: "Assis-debout",
            remarques: "Nette amélioration, pas de douleur signalée",
            results: [
              { field: "Répétitions", chart: true, value: "12" },
              { field: "FC initiale", value: "70" },
              { field: "FC finale", value: "88" },
              { field: "FC après délai", value: "73" },
              { field: "Sat initiale", value: "99" },
              { field: "Sat finale", value: "98" },
              { field: "Sat après délai", value: "99" },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "Légère instabilité côté gauche",
            results: [
              { field: "Durée gauche", chart: true, value: "15" },
              { field: "Durée droite", chart: true, value: "22" },
              { field: "FC initiale", value: "70" },
              { field: "FC finale", value: "74" },
              { field: "FC après délai", value: "71" },
            ],
          },
        ],
      },
      {
        id: "a1b2c3d4-e5f6-7890-abcd-ef1234567890",
        type: "initial",
        height: 165,
        weight: 63,
        imc: 23.14,
        date: "2026-01-10",
        tests: [
          {
            name: "Assis-debout",
            remarques: "Douleurs signalées à la montée",
            results: [
              { field: "Répétitions", chart: true, value: "8" },
              { field: "FC initiale", value: "72" },
              { field: "FC finale", value: "95" },
              { field: "FC après délai", value: "78" },
              { field: "Sat initiale", value: "98" },
              { field: "Sat finale", value: "97" },
              { field: "Sat après délai", value: "98" },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "Légère instabilité côté gauche",
            results: [
              { field: "Durée gauche", chart: true, value: "12" },
              { field: "Durée droite", chart: true, value: "18" },
              { field: "FC initiale", value: "70" },
              { field: "FC finale", value: "74" },
              { field: "FC après délai", value: "71" },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
  {
    id: "3",
    sex: "man",
    lastName: "Schneider",
    firstName: "Marc",
    address: {
      cp: "67200",
      city: "Strasbourg",
      street: "3 allée des Marronniers",
    },
    mail: "m.schneider@free.fr",
    phone: "0623456789",
    birth: "1952-11-05",
    height: 174,
    weight: 78,
    problems: "BPCO modérée, essoufflement à l'effort",
    history: "Fumeur pendant 30 ans, arrêt en 2010. Diagnostic BPCO en 2020.",
    goals: "Améliorer l'endurance pour les activités du quotidien",
    archived: false,
    bilans: [
      {
        id: "c3d4e5f6-a7b8-9012-cdef-123456789012",
        type: "initial",
        height: 174,
        weight: 78,
        imc: 25.7,
        date: "2026-02-03",
        tests: [
          {
            name: "Assis-debout",
            remarques: "Essoufflement marqué en fin de test",
            results: [
              { field: "Répétitions", chart: true, value: "4" },
              { field: "FC initiale", value: "80" },
              { field: "FC finale", value: "115" },
              { field: "FC après délai", value: "92" },
              { field: "Sat initiale", value: "94" },
              { field: "Sat finale", value: "88" },
              { field: "Sat après délai", value: "92" },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "Équilibre correct pour l'âge",
            results: [
              { field: "Durée gauche", chart: true, value: "15" },
              { field: "Durée droite", chart: true, value: "14" },
              { field: "FC initiale", value: "78" },
              { field: "FC finale", value: "82" },
              { field: "FC après délai", value: "79" },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
  {
    id: "4",
    sex: "woman",
    lastName: "Müller",
    firstName: "Ingrid",
    address: {
      cp: "67380",
      city: "Lingolsheim",
      street: "8 rue du Moulin",
    },
    mail: "ingrid.muller@gmail.com",
    phone: "0645678901",
    birth: "1990-02-18",
    height: 170,
    weight: 60,
    problems: "Douleurs à l'épaule droite, tendinite rotateurs",
    history:
      "Sportive de niveau amateur (natation). Début des douleurs en 2025 après reprise intense.",
    goals: "Reprendre la natation compétitive sans douleur",
    archived: false,
    bilans: [
      {
        id: "d4e5f6a7-b8c9-0123-defa-234567890123",
        type: "initial",
        height: 170,
        weight: 60,
        imc: 20.8,
        date: "2026-01-28",
        tests: [
          {
            name: "Test d'équilibre unipodal",
            remarques: "Très bonne stabilité générale",
            results: [
              { field: "Durée gauche", chart: true, value: "30" },
              { field: "Durée droite", chart: true, value: "28" },
              { field: "FC initiale", value: "62" },
              { field: "FC finale", value: "65" },
              { field: "FC après délai", value: "63" },
            ],
          },
          {
            name: "Assis-debout",
            remarques: "Aucune limitation aux membres inférieurs",
            results: [
              { field: "Répétitions", chart: true, value: "15" },
              { field: "FC initiale", value: "64" },
              { field: "FC finale", value: "90" },
              { field: "FC après délai", value: "67" },
              { field: "Sat initiale", value: "99" },
              { field: "Sat finale", value: "99" },
              { field: "Sat après délai", value: "99" },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
  {
    id: "5",
    sex: "man",
    lastName: "Bernard",
    firstName: "Jacques",
    address: {
      cp: "67500",
      city: "Haguenau",
      street: "27 rue du Général de Gaulle",
    },
    mail: "j.bernard@wanadoo.fr",
    phone: "0601234567",
    birth: "1943-09-30",
    height: 168,
    weight: 91,
    problems: "Arthrose des deux genoux, difficultés à la marche",
    history:
      "Prothèse totale genou gauche en 2022. Suivi régulier en rééducation.",
    goals: "Maintenir l'autonomie et éviter une deuxième opération",
    archived: false,
    bilans: [
      {
        id: "e5f6a7b8-c9d0-1234-efab-345678901234",
        type: "initial",
        height: 168,
        weight: 91,
        imc: 32.2,
        date: "2025-06-15",
        tests: [
          {
            name: "Assis-debout",
            remarques: "Aide des mains sur les accoudoirs nécessaire",
            results: [
              { field: "Répétitions", chart: true, value: "3" },
              { field: "FC initiale", value: "76" },
              { field: "FC finale", value: "102" },
              { field: "FC après délai", value: "85" },
              { field: "Sat initiale", value: "96" },
              { field: "Sat finale", value: "94" },
              { field: "Sat après délai", value: "95" },
            ],
          },
          {
            name: "Test d'équilibre unipodal",
            remarques: "Non réalisable côté gauche, douleur trop importante",
            results: [
              { field: "Durée gauche", chart: true, value: "0" },
              { field: "Durée droite", chart: true, value: "6" },
              { field: "FC initiale", value: "75" },
              { field: "FC finale", value: "78" },
              { field: "FC après délai", value: "76" },
            ],
          },
        ],
      },
    ],
    logbook: [],
  },
]
