export const EMPTY_PATIENT = {
  id: "",
  sex: "",
  lastName: "",
  firstName: "",
  address: { cp: "", city: "", street: "" },
  mail: "",
  phone: "",
  birth: "",
  problems: "",
  history: "",
  goals: "",
  height: 0,
  weight: 0,
  bilans: [],
  logbook: [],
}
