import { createContext } from "react"

export const MainContext = createContext({
  addNewPatient: () => {},
  updatePatients: () => {},
  toggleAddPatient: () => {},
  togglePatient: () => {},
  toggleProInfo: () => {},
  toggleNewBilan: () => {},
  isNewBilan: false,
  selectedPatient: {},
  handleSelectedPatient: () => {},
  handleBilanDataChange: () => {},
  updateLogBook: () => {},
  bilanData: {},
  handleResultChange: () => {},
  handleRemarquesChange: () => {},
  testsSelectChange: () => {},
  isOldBilanOpened: false,
  toggleOldBilan: () => {},
  handleSelectedBilan: () => {},
  selectedBilan: null,
  pro: {},
  proSubmit: () => {},
  tourCompleted: false,
  completeTour: () => {},
})
